# Generated by Django 4.2.3 on 2023-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="наименование")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="наименование")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=128, verbose_name="значение")),
                ("detail", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.detail")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.ManyToManyField(
                through="products.ProductDetail", to="products.detail", verbose_name="характеристики"
            ),
        ),
    ]
