# Generated by Django 4.2.3 on 2023-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="цена")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512, verbose_name="название")),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="shops",
                        through="shops.Offer",
                        to="products.product",
                        verbose_name="товары в магазине",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="offer",
            name="shop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shops.shop"),
        ),
    ]
